# Generated by Django 5.1.2 on 2025-02-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='product',
            new_name='category',
        ),
    ]
